### ISSUE TITLE
PS 3.0 not needed

### ISSUE THREAD

**Issue by ToruTheRedFox** [xan1242/nfsc_fixstreakflares#2]
all the techniques in particle.fx can be compiled using vs_1_1 and ps_2_0 and they work just fine, so PS 3.0 is not needed at all

**Comment by ToruTheRedFox** [comment]
odd

**Comment by xan1242** [comment]
Fixed with commit [a5f6714](https://github.com/xan1242/nfsc_fixstreakflares/commit/a5f67140899a66ec0dbbf4585a1513bcc736a08d)
